# @generated by wake_sol._gen.errors_catalog — do not edit.
"""Native System Program error catalog.

Generated from ``wake_sol._gen.errors_catalog`` — do not edit."""


from __future__ import annotations


from .._errors_base import SystemProgramError


class AccountAlreadyInUse(SystemProgramError):
    code = 0
    msg = 'an account with the same address already exists'


class ResultWithNegativeLamports(SystemProgramError):
    code = 1
    msg = 'account does not have enough SOL to perform the operation'


class InvalidProgramId(SystemProgramError):
    code = 2
    msg = 'cannot assign account to this program id'


class InvalidAccountDataLength(SystemProgramError):
    code = 3
    msg = 'cannot allocate account data of this length'


class MaxSeedLengthExceeded(SystemProgramError):
    code = 4
    msg = 'length of requested seed is too long'


class AddressWithSeedMismatch(SystemProgramError):
    code = 5
    msg = 'provided address does not match the address derived from seed'


class NonceNoRecentBlockhashes(SystemProgramError):
    code = 6
    msg = 'advancing stored nonce requires a populated RecentBlockhashes sysvar'


class NonceBlockhashNotExpired(SystemProgramError):
    code = 7
    msg = 'stored nonce is still in recent_blockhashes'


class NonceUnexpectedBlockhashValue(SystemProgramError):
    code = 8
    msg = 'specified nonce does not match stored nonce'


BY_CODE: dict[int, type[SystemProgramError]] = {
    0: AccountAlreadyInUse,
    1: ResultWithNegativeLamports,
    2: InvalidProgramId,
    3: InvalidAccountDataLength,
    4: MaxSeedLengthExceeded,
    5: AddressWithSeedMismatch,
    6: NonceNoRecentBlockhashes,
    7: NonceBlockhashNotExpired,
    8: NonceUnexpectedBlockhashValue,
}
