"""Emit a generated pytypes module as source text, shaped exactly like
``tests/fixture_program.py`` (§6.1): ``from __future__`` -> imports ->
PROGRAM_ID/PROGRAM_NAME -> (1) types -> (2) accounts -> (5) builder class ->
(6) ``register(...)`` -> provenance footer.

Sections: (1) types -> (2) accounts -> (3) events -> (4) errors -> (5) builder ->
(6) register. Events are emitted as discriminator-carrying ``BorshStruct``s
(``Kind.EVENT``) and registered so ``emit!``/``emit_cpi!`` payloads decode (§10.3
AS BUILT). The emitter validates nothing at runtime itself; a mis-emitted
annotation surfaces loudly as a ``GenError`` when the module imports (fail-loud
feedback loop, §9 gotchas).
"""

from __future__ import annotations

from .._codec import GenError, mangle
from . import wellknown
from .types import Usage, map_type

BANNER = "# GENERATED by `solana-fuzzer gen` — do not edit. Provenance pinned below."
NOTE_EVENTS = "# NOTE: instructions, accounts, events, and errors are emitted; §10.1 log-scan events decode at runtime."

# Canonical import ordering (deterministic output for the --check gate).
_ALIAS_ORDER = ["u8", "u16", "u32", "u64", "u128", "u256",
                "i8", "i16", "i32", "i64", "i128", "i256",
                "f32", "f64", "char", "pubkey"]
_ENGINE_ORDER = [
    "Opt", "BorshEnumMeta", "BorshStruct", "variant",
    "AccountSlot", "BorshMeta", "InstructionMeta", "Kind", "MetaLike",
    "Serialization", "instruction", "build_interface_from_module",
    "compile_layout", "encode_ix_layout", "build_metas", "slot", "as_meta",
]
_TYPING_ORDER = ["Annotated", "Optional", "Sequence"]


def _pascal(name: str) -> str:
    """snake_case / kebab-case IDL name -> a PascalCase builder-class identifier."""
    parts = [p for p in name.replace("-", "_").split("_") if p]
    cls = "".join(p[:1].upper() + p[1:] for p in parts) or "Program"
    if cls[0].isdigit():
        cls = "P" + cls
    return cls


def _bytes_literal(b: bytes) -> str:
    return 'b"' + "".join(f"\\x{x:02x}" for x in b) + '"'


def _field_lines(fields, usage, indent="    "):
    """Render dataclass field annotations. Tuple fields (no IDL name) become
    ``_0, _1, …``; an empty field list is ``pass``."""
    if not fields:
        return [f"{indent}pass"]
    lines = []
    for i, f in enumerate(fields):
        fname = mangle(f.name) if f.name is not None else f"_{i}"
        lines.append(f"{indent}{fname}: {map_type(f.type, usage)}")
    return lines


class ModuleEmitter:
    def __init__(self, idl, provenance, source_locations=None):
        self.idl = idl
        self.provenance = provenance
        # {instruction_name: "file:///…#Lline"} for `--source-links`; empty when off
        # or unresolved. Emitted as a builder-method docstring (see _emit_instruction).
        self.source_locations = source_locations or {}
        self.usage = Usage()
        self.engine = set()             # extra _codec symbols (non-alias/carrier)
        self.layouts = []               # [(const_name, [ann_str])] encode layouts
        self.need_dataclass = False
        self.need_intenum = False
        self.need_instruction_meta = False

    # -- types ------------------------------------------------------------- #
    def _emit_enum(self, tdef):
        all_unit = all(not v.fields for v in tdef.variants)
        if all_unit:
            self.need_intenum = True
            lines = [f"class {tdef.name}(IntEnum):"]
            for i, v in enumerate(tdef.variants):
                lines.append(f"    {v.name} = {i}")
            return "\n".join(lines)

        self.need_dataclass = True
        self.engine.update({"BorshEnumMeta", "variant"})
        lines = [f"class {tdef.name}(metaclass=BorshEnumMeta):"]
        for i, v in enumerate(tdef.variants):
            lines.append("")
            lines.append(f"    @variant({i})")
            lines.append("    @dataclass")
            lines.append(f"    class {v.name}:")
            lines.extend(_field_lines(v.fields, self.usage, indent="        "))
        return "\n".join(lines)

    def _emit_struct(self, tdef, borsh_meta_disc=None, kind="ACCOUNT"):
        self.need_dataclass = True
        self.engine.add("BorshStruct")
        lines = ["@dataclass", f"class {tdef.name}(BorshStruct):"]
        lines.extend(_field_lines(tdef.fields, self.usage))
        if borsh_meta_disc is not None:
            # `kind` is ACCOUNT (disc + slack-tolerant body) or EVENT (disc +
            # strict body); both prepend/strip the discriminator on encode/decode.
            self.engine.update({"BorshMeta", "Kind", "Serialization"})
            lines.append("")
            lines.append("    __borsh_meta__ = BorshMeta(")
            lines.append("        ser=Serialization.BORSH,")
            lines.append(f"        kind=Kind.{kind},")
            lines.append(f"        is_account_root={kind == 'ACCOUNT'},")
            lines.append(f"        discriminator={_bytes_literal(borsh_meta_disc)},")
            lines.append(f"        discriminator_len={len(borsh_meta_disc)},")
            lines.append("    )")
        return "\n".join(lines)

    def _emit_typedef(self, tdef, borsh_meta_disc=None, kind="ACCOUNT"):
        if tdef.serialization != "borsh":
            raise GenError(f"type {tdef.name!r} has serialization="
                           f"{tdef.serialization!r}; v1 engine is Borsh-only")
        if tdef.kind == "enum":
            if borsh_meta_disc is not None:
                raise GenError(f"{kind.lower()} {tdef.name!r} is an enum; "
                               "discriminator-carrying enums are not supported in v1")
            return self._emit_enum(tdef)
        return self._emit_struct(tdef, borsh_meta_disc, kind)

    # -- instructions ------------------------------------------------------ #
    def _emit_instruction(self, ix):
        self.need_instruction_meta = True
        self.engine.update({"AccountSlot", "InstructionMeta", "instruction",
                            "compile_layout", "encode_ix_layout", "build_metas",
                            "slot", "as_meta", "MetaLike"})
        self.usage.typing.add("Sequence")
        disc = _bytes_literal(ix.discriminator)

        # signature pieces. The arg annotations feed a module-level layout that
        # is compiled once at import (see render()); the call site passes only
        # the values, so nothing is lowered on the encode hot path.
        data_params, value_names, layout_anns = [], [], []
        seen = {}
        for arg in ix.args:
            pname = mangle(arg.name)
            if pname in seen:
                raise GenError(f"instruction {ix.name!r}: arg name collision on "
                               f"{pname!r}")
            seen[pname] = True
            ann = map_type(arg.type, self.usage)
            data_params.append(f"{pname}: {ann}")
            value_names.append(pname)
            layout_anns.append(ann)

        acct_params, slot_calls, slot_specs = [], [], []
        for a in ix.accounts:
            pname = mangle(a.name)
            if pname in seen:
                raise GenError(f"instruction {ix.name!r}: account name collision "
                               f"on {pname!r}")
            seen[pname] = True
            # Fixed-address accounts default to that pubkey (IDL `address` is
            # authoritative; else a well-known account name — see wellknown.py).
            default_addr = a.address or wellknown.resolve(a.name)
            if default_addr is not None:
                ann = "MetaLike | None" if a.is_optional else "MetaLike"
                acct_params.append(f'{pname}: {ann} = Pubkey("{default_addr}")')
            elif a.is_optional:
                acct_params.append(f"{pname}: MetaLike | None = None")
            else:
                acct_params.append(f"{pname}: MetaLike")
            slot_calls.append(
                f"slot({pname}, {a.is_signer}, {a.is_writable}, {a.is_optional})")
            slot_specs.append(self._account_slot(a))

        # decorator
        if slot_specs:
            acct_block = "\n".join(f"            {s}," for s in slot_specs)
            accounts_arg = f"accounts=(\n{acct_block}\n        ),"
        else:
            accounts_arg = "accounts=(),"
        # `returns` type (Anchor 0.30+): carried on the meta so the runtime can
        # decode return data to it (result.return_value). Uses the same mapper as
        # args, so it round-trips through import-time compile_field. The mapped
        # annotation also parameterizes the builder's return — `Instruction[T]` —
        # so `T` flows to `TransactionResult[T]` via the single-ix `tx`/`simulate`
        # overloads and the linter knows `result.return_value`'s type.
        returns_line = ""
        ret_hint = "Instruction"
        if ix.returns is not None:
            returns_ann = map_type(ix.returns, self.usage)
            returns_line = f"        returns_type={returns_ann},\n"
            ret_hint = f"Instruction[{returns_ann}]"
        # `@classmethod` wraps `@instruction(...)` (outermost), so the builder is
        # callable as `Program.ix(...)` with no pointless instantiation. The
        # introspection in build_interface_from_module() sees through the bound
        # classmethod (`__pytypes_ix__` forwards via `__func__`) and
        # inspect.signature already drops `cls`, so the derived decode layout is
        # unchanged. Calling through an instance still works, so this is
        # backwards compatible with `Program().ix(...)`.
        deco = (f"    @classmethod\n"
                f"    @instruction(InstructionMeta(\n"
                f'        name="{ix.name}",\n'
                f"        discriminator={disc},\n"
                f"        {accounts_arg}\n"
                f"{returns_line}"
                f"    ))")

        # signature line(s)
        kw_params = acct_params + ["remaining_accounts: Sequence[MetaLike] = ()"]
        head = f"    def {mangle(ix.name)}(cls"
        if data_params:
            head += ", " + ", ".join(data_params)
        sig = f"{head}, *, {', '.join(kw_params)}) -> {ret_hint}:"

        # body
        body = []
        if value_names:
            layout_name = f"_ENC_{mangle(ix.name)}"
            self.layouts.append((layout_name, layout_anns))
            body.append(f"        data = encode_ix_layout({disc}, {layout_name}, "
                        f"{', '.join(value_names)})")
        else:
            body.append(f"        data = encode_ix_layout({disc}, ())")
        if slot_calls:
            inner = "\n".join(f"            {c}," for c in slot_calls)
            body.append(f"        metas = build_metas(\n            PROGRAM_ID,\n{inner}\n        )")
        else:
            body.append("        metas = build_metas(PROGRAM_ID)")
        body.append("        metas += [as_meta(m) for m in remaining_accounts]")
        body.append("        return Instruction(PROGRAM_ID, metas, data)")

        return deco + "\n" + sig + "\n" + "\n".join(body)

    def _account_slot(self, a):
        kwargs = []
        if a.is_signer:
            kwargs.append("is_signer=True")
        if a.is_writable:
            kwargs.append("is_writable=True")
        if a.is_optional:
            kwargs.append("is_optional=True")
        joined = (", " + ", ".join(kwargs)) if kwargs else ""
        return f'AccountSlot("{a.name}"{joined})'

    # -- assembly ---------------------------------------------------------- #
    # -- errors ------------------------------------------------------------ #
    def _emit_errors(self, base_name):
        """One exception class per IDL ``errors[]`` entry, under a per-program
        base (a ``ProgramError`` subclass). Codes copied verbatim; ``register_errors``
        wires them into the raise-path resolver. See design/pytypes §10.2."""
        blocks = [
            f"class {base_name}(ProgramError):\n"
            f'    """Base for every {self.idl.name} program error — '
            f"catch it to match any of them.\"\"\""
        ]
        for e in self.idl.errors:
            lines = [f"class {e.name}({base_name}):", f"    code = {e.code}"]
            if e.msg is not None:
                lines.append(f"    msg = {e.msg!r}")
            blocks.append("\n".join(lines))
        blocks.append(f"register_errors({base_name})")
        return blocks

    def _imports(self):
        out = []

        future = "from __future__ import annotations"

        stdlib = []
        if self.need_dataclass:
            stdlib.append("from dataclasses import dataclass")
        if self.need_intenum:
            stdlib.append("from enum import IntEnum")
        typing_used = [t for t in _TYPING_ORDER if t in self.usage.typing]
        if typing_used:
            stdlib.append(f"from typing import {', '.join(typing_used)}")

        # engine (_codec)
        codec_syms = []
        codec_syms += [a for a in _ALIAS_ORDER if a in self.usage.aliases]
        engine_set = set(self.engine) | set(self.usage.carriers)
        engine_set.add("build_interface_from_module")
        codec_syms += [s for s in _ENGINE_ORDER if s in engine_set]

        native_syms = ["Pubkey"]
        if self.idl.instructions:
            native_syms.insert(0, "Instruction")

        out.append(future)
        out.append("")
        out.extend(stdlib)
        if stdlib:
            out.append("")
        out.append(self._from_import("solana_fuzzer._codec", codec_syms))
        out.append("from solana_fuzzer._interface import register")
        if self.idl.errors:
            out.append("from solana_fuzzer._errors import ProgramError, register_errors")
        out.append(self._from_import("solana_fuzzer._native", native_syms))
        return "\n".join(out)

    @staticmethod
    def _from_import(module, symbols):
        if len(symbols) <= 3:
            return f"from {module} import {', '.join(symbols)}"
        body = "".join(f"    {s},\n" for s in symbols)
        return f"from {module} import (\n{body})"

    def _provenance_literal(self):
        p = self.provenance
        order = ["schema_version", "program_address", "program_name", "module",
                 "source_root", "idl_path", "idl_sha256", "anchor_version",
                 "generator_version", "verified"]
        lines = ["__provenance__ = {"]
        for k in order:
            v = p.get(k)
            if isinstance(v, bool):
                lit = "True" if v else "False"
            elif v is None:
                lit = "None"
            else:
                lit = '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'
            lines.append(f'    "{k}": {lit},')
        lines.append("}")
        return "\n".join(lines)

    def render(self):
        idl = self.idl
        cls_name = _pascal(idl.name)
        layouts = idl.type_layouts
        account_names = idl.account_names
        event_names = idl.event_names

        # (1) types — non-account, non-event type defs, IDL declaration order
        type_blocks = []
        for tdef in idl.types:
            if tdef.name in account_names or tdef.name in event_names:
                continue
            type_blocks.append(self._emit_typedef(tdef))

        # (2) accounts — account decl order, layout pulled from the type table
        account_blocks = []
        for acc in idl.accounts:
            tdef = layouts.get(acc.name)
            if tdef is None:
                raise GenError(f"account {acc.name!r} has no layout in the IDL "
                               "types[] table")
            account_blocks.append(self._emit_typedef(tdef, borsh_meta_disc=acc.discriminator))

        # (3) events — event decl order, layout from the type table; emitted as
        # discriminator-carrying BorshStructs (Kind.EVENT), registered by the
        # self-register call so `Program data:`/`emit_cpi!` payloads decode.
        event_blocks = []
        for ev in idl.events:
            tdef = layouts.get(ev.name)
            if tdef is None:
                raise GenError(f"event {ev.name!r} has no layout in the IDL "
                               "types[] table")
            event_blocks.append(
                self._emit_typedef(tdef, borsh_meta_disc=ev.discriminator, kind="EVENT"))

        # (5) builder class
        method_blocks = [self._emit_instruction(ix) for ix in idl.instructions]

        # imports depend on usage accumulated above
        imports = self._imports()

        program_id = (f'PROGRAM_ID = Pubkey("{idl.address}")\n'
                      f'PROGRAM_NAME = "{idl.name}"')

        sep = "\n\n\n"
        parts = [BANNER + "\n" + NOTE_EVENTS, imports, program_id]
        if type_blocks:
            parts.append(_section("1. types") + "\n" + "\n\n\n".join(type_blocks))
        if account_blocks:
            parts.append(_section("2. accounts") + "\n" + "\n\n\n".join(account_blocks))
        if event_blocks:
            parts.append(_section("3. events") + "\n" + "\n\n\n".join(event_blocks))
        if idl.errors:
            parts.append(_section("4. errors") + "\n"
                         + "\n\n\n".join(self._emit_errors(f"{cls_name}Error")))

        cls_lines = [_section("5. instructions / builder")]
        if self.layouts:
            # Encode layouts — compiled once at import (the encode-side mirror of
            # the decode layout built at registration). Placed after the type
            # sections so every referenced type is already defined; referenced by
            # name from the builder methods below.
            cls_lines.extend(f"{name} = compile_layout({', '.join(anns)})"
                             for name, anns in self.layouts)
            cls_lines.append("")
        cls_lines += [f"class {cls_name}:",
                      "    program_id = PROGRAM_ID"]
        if method_blocks:
            cls_body = "\n\n".join(method_blocks)
            cls_lines.append("")
            cls_lines.append(cls_body)
        parts.append("\n".join(cls_lines))

        parts.append(_section("6. self-register (import side effect)") + "\n" +
                     f"register(build_interface_from_module("
                     f"__name__, {cls_name}, PROGRAM_ID, PROGRAM_NAME))")
        parts.append("# --- provenance (pinned; see §9.4) ---\n" +
                     self._provenance_literal())
        return sep.join(parts) + "\n"


def _section(title):
    bar = "# " + "-" * 73 + " #"
    return f"{bar}\n# {title}\n{bar}"


def emit_module(idl, provenance) -> str:
    """Render the full generated module source for ``idl``."""
    return ModuleEmitter(idl, provenance).render()
