"""Discovery, package emission, provenance, determinism, and the ``--check``
drift gate (§9.1–9.10). ``run_gen`` is the entry point the CLI invokes; it
returns a process exit code (0 ok, 2 gen-error/strict/drift).
"""

from __future__ import annotations

import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

from . import GENERATOR_VERSION, SCHEMA_VERSION
from .._codec import GenError
from .emit import emit_module
from .idl import load_idl

# Reasons attached to whole-program refusal stubs.
_REFUSAL_REASON = "generation_punt"


def _log(verbose, msg):
    if verbose:
        print(f"[gen] {msg}", file=sys.stderr)


def _warn(msg):
    print(f"[gen] warning: {msg}", file=sys.stderr)


# --------------------------------------------------------------------------- #
# discovery + keying (§9.1, §9.7)
# --------------------------------------------------------------------------- #
def _collect(roots, label, verbose):
    """Address -> (idl, path) for one source. Duplicate address within a single
    source is a hard error (ambiguous input)."""
    out = {}
    for root in roots:
        root = Path(root)
        if not root.exists():
            _warn(f"{label} root {root} does not exist (skipping)")
            continue
        for path in sorted(root.glob("*.json")):
            if path.name.endswith(".facts.json"):
                continue
            idl = load_idl(path)
            if idl.address in out:
                raise GenError(
                    f"duplicate address {idl.address} under {label}: "
                    f"{out[idl.address][1]} and {path}")
            out[idl.address] = (idl, path)
            _log(verbose, f"discovered {idl.address} <- {path} ({label})")
    return out


def _discover(target_roots, dep_roots, verbose):
    """Merge the two sources; ``target/idl`` wins on address collision."""
    deps = _collect(dep_roots, "idls", verbose)
    targets = _collect(target_roots, "target/idl", verbose)
    merged = {}
    for addr, (idl, path) in deps.items():
        merged[addr] = (idl, path, "idls")
    for addr, (idl, path) in targets.items():
        if addr in merged:
            _warn(f"address {addr} present under both roots; target/idl wins")
        merged[addr] = (idl, path, "target/idl")
    return merged


# --------------------------------------------------------------------------- #
# module naming (§9.3.1)
# --------------------------------------------------------------------------- #
def _slugify(name):
    out = []
    for ch in name:
        out.append(ch if (ch.isalnum() or ch == "_") else "_")
    slug = "".join(out).strip("_").lower()
    while "__" in slug:
        slug = slug.replace("__", "_")
    if not slug:
        slug = "program"
    if slug[0].isdigit():
        slug = "p_" + slug
    return slug


def _assign_modules(programs):
    """programs: list of (addr, idl, path, source). Return addr -> module slug,
    disambiguating slug collisions by a 6-char address suffix (address remains
    the source of truth)."""
    by_slug = {}
    for addr, idl, _path, _src in programs:
        by_slug.setdefault(_slugify(idl.name), []).append(addr)
    modules = {}
    for slug, addrs in by_slug.items():
        if len(addrs) == 1:
            modules[addrs[0]] = slug
        else:
            for addr in addrs:                       # collision -> address suffix
                modules[addr] = f"{slug}_{addr[:6]}"
    # A same-slug AND same-address situation is impossible here (addresses are
    # unique keys); identical addresses would have collapsed during discovery.
    return modules


# --------------------------------------------------------------------------- #
# provenance (§9.4)
# --------------------------------------------------------------------------- #
def _provenance(idl, module, path, source, generated_at, refusal_reason=None):
    prov = {
        "schema_version": SCHEMA_VERSION,
        "program_address": idl.address,
        "program_name": idl.name,
        "module": module,
        "source_root": source,
        "idl_path": str(path),
        "idl_sha256": idl.idl_sha256,
        "anchor_version": idl.anchor_version,
        "generator_version": GENERATOR_VERSION,
        "verified": False,
    }
    if refusal_reason is not None:
        prov["refusal_reason"] = refusal_reason
    # generated_at lives only in the manifest (kept out of module files so they
    # are byte-deterministic for --check); recorded here for the manifest copy.
    prov_with_ts = dict(prov)
    prov_with_ts["generated_at"] = generated_at
    return prov, prov_with_ts


def _refusing_stub(idl, prov, reason):
    return (
        "# GENERATED by `solana-fuzzer gen` — do not edit. Refusing stub (§9.8).\n"
        "from solana_fuzzer._interface import RefusingInterface, register\n"
        "from solana_fuzzer._native import Pubkey\n\n\n"
        f'PROGRAM_ID = Pubkey("{idl.address}")\n'
        f'PROGRAM_NAME = "{idl.name}"\n\n\n'
        "register(RefusingInterface(\n"
        f"    str(PROGRAM_ID), PROGRAM_NAME, reason={reason!r}))\n\n\n"
        "# --- provenance (pinned; see §9.4) ---\n"
        + _emit_prov_literal(prov) + "\n"
    )


def _emit_prov_literal(prov):
    lines = ["__provenance__ = {"]
    for k, v in prov.items():
        if isinstance(v, bool):
            lit = "True" if v else "False"
        elif v is None:
            lit = "None"
        else:
            lit = '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'
        lines.append(f'    "{k}": {lit},')
    lines.append("}")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# package assembly
# --------------------------------------------------------------------------- #
def _init_module(modules_in_order):
    lines = ['"""Generated by `solana-fuzzer gen`. Importing this package registers',
             "every program below into solana_fuzzer._interface.REGISTRY (import",
             'side effect)."""']
    for m in modules_in_order:
        lines.append(f"from . import {m} as {m}  # noqa: F401")
    names = ", ".join(f'"{m}"' for m in modules_in_order)
    lines.append("")
    lines.append(f"__all__ = [{names}]")
    lines.append(f'__generated_by__ = "{GENERATOR_VERSION}"')
    return "\n".join(lines) + "\n"


def _build_files(programs, modules, strict, verbose):
    """Return (files: dict[name -> content], manifest: dict). ``programs`` is in
    ascending base58 address order."""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    files = {}
    manifest = {}
    module_order = []
    for addr, idl, path, source in programs:
        module = modules[addr]
        module_order.append(module)
        try:
            prov, prov_ts = _provenance(idl, module, path, source, generated_at)
            content = emit_module(idl, prov)
            _log(verbose, f"emitted {module}.py for {addr}")
        except GenError as exc:
            if strict:
                raise GenError(f"{addr} ({idl.name}): {exc}") from exc
            reason = f"{_REFUSAL_REASON}: {exc}"
            prov, prov_ts = _provenance(idl, module, path, source, generated_at,
                                        refusal_reason=reason)
            content = _refusing_stub(idl, prov, reason)
            _warn(f"{addr} ({idl.name}) refused: {exc} -> emitting refusing stub")
        files[f"{module}.py"] = content
        manifest[addr] = prov_ts

    files["__init__.py"] = _init_module(module_order)
    files["_manifest.json"] = json.dumps(manifest, indent=2) + "\n"
    return files, manifest


# --------------------------------------------------------------------------- #
# write / check
# --------------------------------------------------------------------------- #
def _write_package(out_dir, files):
    out_dir = Path(out_dir)
    tmp = out_dir.parent / (out_dir.name + ".tmp")
    if tmp.exists():
        shutil.rmtree(tmp)
    tmp.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (tmp / name).write_text(content)
    if out_dir.exists():
        shutil.rmtree(out_dir)
    tmp.rename(out_dir)


def _strip_generated_at(manifest_text):
    try:
        data = json.loads(manifest_text)
    except (ValueError, TypeError):
        return manifest_text
    for entry in data.values():
        entry.pop("generated_at", None)
    return json.dumps(data, indent=2, sort_keys=True)


def _check(out_dir, files):
    """Return a list of drift descriptions ([] == in sync)."""
    out_dir = Path(out_dir)
    drift = []
    existing = ({p.name: p for p in out_dir.iterdir() if p.is_file()}
                if out_dir.exists() else {})
    for name, content in files.items():
        if name not in existing:
            drift.append(f"missing committed file: {name}")
            continue
        old = existing[name].read_text()
        if name == "_manifest.json":
            if _strip_generated_at(old) != _strip_generated_at(content):
                drift.append(f"manifest drift: {name}")
        elif old != content:
            drift.append(f"content drift: {name}")
    for name in existing:
        if name not in files and (name.endswith(".py") or name == "_manifest.json"):
            drift.append(f"stale committed file: {name}")
    return drift


# --------------------------------------------------------------------------- #
# entry point
# --------------------------------------------------------------------------- #
def run_gen(target_idls=("target/idl",), dep_idls=("idls",), out="pytypes",
            only=(), check=False, no_facts=False, strict=False, verify=False,
            allow_unverified=False, verbose=0):
    try:
        if verify and not allow_unverified:
            _warn("the --verify gate is deferred in v1 (§12.3); emitting "
                  "verified=false. Use --allow-unverified to silence this.")
        if no_facts:
            _log(verbose, "facts sidecars are not consumed in v1 (--no-facts no-op)")

        discovered = _discover(target_idls, dep_idls, verbose)
        if only:
            wanted = set(only)
            discovered = {a: v for a, v in discovered.items() if a in wanted}
            missing = wanted - set(discovered)
            if missing:
                _warn(f"--only addresses not found: {', '.join(sorted(missing))}")
        if not discovered:
            _warn("no IDLs discovered; nothing to generate")

        # deterministic: ascending base58 address order
        programs = [(addr, idl, path, src)
                    for addr, (idl, path, src) in sorted(discovered.items())]
        modules = _assign_modules(programs)
        files, _manifest = _build_files(programs, modules, strict, verbose)

        if check:
            drift = _check(out, files)
            if drift:
                print("gen --check: pytypes/ is out of sync with the IDLs:",
                      file=sys.stderr)
                for d in drift:
                    print(f"  - {d}", file=sys.stderr)
                return 2
            _log(verbose, "--check: in sync")
            return 0

        _write_package(out, files)
        _log(verbose, f"wrote {len(programs)} program module(s) to {out}")
        return 0
    except GenError as exc:
        print(f"[gen] error: {exc}", file=sys.stderr)
        return 2
