"""Base classes for the structured-error hierarchy (see ``_errors`` for the full
overview, ``build()`` resolution, and the ``must_revert`` / ``may_revert`` API).

This module holds only the hand-written category bases. The concrete leaf classes
(``AnchorError.ConstraintSeeds`` etc.) are real classes in the generated
``_errors_catalog`` package and are attached onto these bases at runtime by
``_errors`` (via ``setattr``). To keep the ``Base.LeafName`` spelling visible to
type checkers, each base re-declares its leaves under ``if TYPE_CHECKING:`` — the
blocks between the ``>>>GEN:<cat>>>>`` markers are generated by
``wake_sol._gen.errors_catalog`` and must not be hand-edited.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._native import CallTrace


class TransactionFailed(Exception):
    """Base for every failed transaction. Subclasses identify the specific error;
    instances carry the error scalars and a link to the execution receipt."""

    code: int | None = None   # class attr for code-keyed errors (Anchor/program); None for native
    msg: str | None = None    # class attr: the IDL/framework message, if known

    def __init__(self, *, code=None, instruction_index=None, account_index=None, tx=None):
        self.code = type(self).code if code is None else code
        self.instruction_index = instruction_index
        self.account_index = account_index
        self.tx = tx  # the TransactionResult receipt (set by the runtime); tx.error is self
        super().__init__(self._headline())

    def _headline(self) -> str:
        head = type(self).__name__
        detail = []
        if self.code is not None:
            detail.append(f"code={self.code}")
        if self.instruction_index is not None:
            detail.append(f"ix={self.instruction_index}")
        if self.account_index is not None:
            detail.append(f"account_index={self.account_index}")
        if detail:
            head = f"{head}({', '.join(detail)})"
        return f"{head}: {type(self).msg}" if type(self).msg else head

    def __repr__(self) -> str:  # never expands self.tx -> no cycle recursion
        return f"<{self._headline()}>"

    def __eq__(self, other: object) -> bool:
        """Compare against a sibling instance *or* against a class::

            err == my_program.EmptyVault()    # same error, same code
            err == my_program.EmptyVault      # isinstance test (no parentheses)
            err == my_program.MyProgramError  # any error from that program
            err == ProgramError               # any program-defined code

        Positional detail (``instruction_index`` / ``account_index`` / ``tx``) is
        deliberately ignored: it records *where* the error surfaced, not *which*
        error it is. Compare those fields explicitly when they matter.

        This is sugar over the type matching that ``must_revert``/``may_revert``
        already do — deliberately *not* a value model: no ``program_id``, no CPI
        attribution, nothing beyond the type and the code.
        """
        if isinstance(other, type):
            if issubclass(other, TransactionFailed):
                return isinstance(self, other)
            return NotImplemented
        if isinstance(other, TransactionFailed):
            return type(self) is type(other) and self.code == other.code
        return NotImplemented

    # Defining __eq__ would otherwise set __hash__ to None and make every error
    # unhashable. Keyed on what __eq__ compares, so equal instances hash equal.
    def __hash__(self) -> int:
        return hash((type(self), self.code))

    @property
    def call_trace(self) -> "CallTrace":
        """Shortcut for ``self.tx.call_trace`` (the execution as a rendered
        ``CallTrace``). Raises if this error has no linked receipt — e.g. one
        built directly via :func:`build` rather than raised by the runtime."""
        if self.tx is None:
            raise ValueError("no transaction receipt linked to this error "
                             "(built directly, not raised by the runtime)")
        return self.tx.call_trace


# --- category bases -------------------------------------------------------- #
class SolanaError(TransactionFailed):
    """A Solana runtime error (tx-level or instruction-level, name-keyed)."""

    if TYPE_CHECKING:  # leaf classes attached at runtime; declared here for typing
        # >>>GEN:solana>>>
        from ._errors_catalog.solana import (
            GenericError as GenericError,
            InvalidArgument as InvalidArgument,
            InvalidInstructionData as InvalidInstructionData,
            InvalidAccountData as InvalidAccountData,
            AccountDataTooSmall as AccountDataTooSmall,
            InsufficientFunds as InsufficientFunds,
            IncorrectProgramId as IncorrectProgramId,
            MissingRequiredSignature as MissingRequiredSignature,
            AccountAlreadyInitialized as AccountAlreadyInitialized,
            UninitializedAccount as UninitializedAccount,
            UnbalancedInstruction as UnbalancedInstruction,
            ModifiedProgramId as ModifiedProgramId,
            ExternalAccountLamportSpend as ExternalAccountLamportSpend,
            ExternalAccountDataModified as ExternalAccountDataModified,
            ReadonlyLamportChange as ReadonlyLamportChange,
            ReadonlyDataModified as ReadonlyDataModified,
            DuplicateAccountIndex as DuplicateAccountIndex,
            ExecutableModified as ExecutableModified,
            RentEpochModified as RentEpochModified,
            NotEnoughAccountKeys as NotEnoughAccountKeys,
            AccountDataSizeChanged as AccountDataSizeChanged,
            AccountNotExecutable as AccountNotExecutable,
            AccountBorrowFailed as AccountBorrowFailed,
            AccountBorrowOutstanding as AccountBorrowOutstanding,
            DuplicateAccountOutOfSync as DuplicateAccountOutOfSync,
            InvalidError as InvalidError,
            ExecutableDataModified as ExecutableDataModified,
            ExecutableLamportChange as ExecutableLamportChange,
            ExecutableAccountNotRentExempt as ExecutableAccountNotRentExempt,
            UnsupportedProgramId as UnsupportedProgramId,
            CallDepth as CallDepth,
            MissingAccount as MissingAccount,
            ReentrancyNotAllowed as ReentrancyNotAllowed,
            MaxSeedLengthExceeded as MaxSeedLengthExceeded,
            InvalidSeeds as InvalidSeeds,
            InvalidRealloc as InvalidRealloc,
            ComputationalBudgetExceeded as ComputationalBudgetExceeded,
            PrivilegeEscalation as PrivilegeEscalation,
            ProgramEnvironmentSetupFailure as ProgramEnvironmentSetupFailure,
            ProgramFailedToComplete as ProgramFailedToComplete,
            ProgramFailedToCompile as ProgramFailedToCompile,
            Immutable as Immutable,
            IncorrectAuthority as IncorrectAuthority,
            BorshIoError as BorshIoError,
            AccountNotRentExempt as AccountNotRentExempt,
            InvalidAccountOwner as InvalidAccountOwner,
            ArithmeticOverflow as ArithmeticOverflow,
            UnsupportedSysvar as UnsupportedSysvar,
            IllegalOwner as IllegalOwner,
            MaxAccountsDataAllocationsExceeded as MaxAccountsDataAllocationsExceeded,
            MaxAccountsExceeded as MaxAccountsExceeded,
            MaxInstructionTraceLengthExceeded as MaxInstructionTraceLengthExceeded,
            BuiltinProgramsMustConsumeComputeUnits as BuiltinProgramsMustConsumeComputeUnits,
            AccountInUse as AccountInUse,
            AccountLoadedTwice as AccountLoadedTwice,
            AccountNotFound as AccountNotFound,
            ProgramAccountNotFound as ProgramAccountNotFound,
            InsufficientFundsForFee as InsufficientFundsForFee,
            InvalidAccountForFee as InvalidAccountForFee,
            AlreadyProcessed as AlreadyProcessed,
            BlockhashNotFound as BlockhashNotFound,
            CallChainTooDeep as CallChainTooDeep,
            MissingSignatureForFee as MissingSignatureForFee,
            InvalidAccountIndex as InvalidAccountIndex,
            SignatureFailure as SignatureFailure,
            InvalidProgramForExecution as InvalidProgramForExecution,
            SanitizeFailure as SanitizeFailure,
            ClusterMaintenance as ClusterMaintenance,
            WouldExceedMaxBlockCostLimit as WouldExceedMaxBlockCostLimit,
            UnsupportedVersion as UnsupportedVersion,
            InvalidWritableAccount as InvalidWritableAccount,
            WouldExceedMaxAccountCostLimit as WouldExceedMaxAccountCostLimit,
            WouldExceedAccountDataBlockLimit as WouldExceedAccountDataBlockLimit,
            TooManyAccountLocks as TooManyAccountLocks,
            AddressLookupTableNotFound as AddressLookupTableNotFound,
            InvalidAddressLookupTableOwner as InvalidAddressLookupTableOwner,
            InvalidAddressLookupTableData as InvalidAddressLookupTableData,
            InvalidAddressLookupTableIndex as InvalidAddressLookupTableIndex,
            InvalidRentPayingAccount as InvalidRentPayingAccount,
            WouldExceedMaxVoteCostLimit as WouldExceedMaxVoteCostLimit,
            WouldExceedAccountDataTotalLimit as WouldExceedAccountDataTotalLimit,
            DuplicateInstruction as DuplicateInstruction,
            InsufficientFundsForRent as InsufficientFundsForRent,
            MaxLoadedAccountsDataSizeExceeded as MaxLoadedAccountsDataSizeExceeded,
            InvalidLoadedAccountsDataSizeLimit as InvalidLoadedAccountsDataSizeLimit,
            ResanitizationNeeded as ResanitizationNeeded,
            ProgramExecutionTemporarilyRestricted as ProgramExecutionTemporarilyRestricted,
            UnbalancedTransaction as UnbalancedTransaction,
            ProgramCacheHitMaxLimit as ProgramCacheHitMaxLimit,
            CommitCancelled as CommitCancelled,
        )
        # <<<GEN:solana<<<


class AnchorError(TransactionFailed):
    """An Anchor framework error (built-in code < 6000)."""

    if TYPE_CHECKING:
        # >>>GEN:anchor>>>
        from ._errors_catalog.anchor import (
            InstructionMissing as InstructionMissing,
            InstructionFallbackNotFound as InstructionFallbackNotFound,
            InstructionDidNotDeserialize as InstructionDidNotDeserialize,
            InstructionDidNotSerialize as InstructionDidNotSerialize,
            IdlInstructionStub as IdlInstructionStub,
            IdlInstructionInvalidProgram as IdlInstructionInvalidProgram,
            IdlAccountNotEmpty as IdlAccountNotEmpty,
            EventInstructionStub as EventInstructionStub,
            ConstraintMut as ConstraintMut,
            ConstraintHasOne as ConstraintHasOne,
            ConstraintSigner as ConstraintSigner,
            ConstraintRaw as ConstraintRaw,
            ConstraintOwner as ConstraintOwner,
            ConstraintRentExempt as ConstraintRentExempt,
            ConstraintSeeds as ConstraintSeeds,
            ConstraintExecutable as ConstraintExecutable,
            ConstraintState as ConstraintState,
            ConstraintAssociated as ConstraintAssociated,
            ConstraintAssociatedInit as ConstraintAssociatedInit,
            ConstraintClose as ConstraintClose,
            ConstraintAddress as ConstraintAddress,
            ConstraintZero as ConstraintZero,
            ConstraintTokenMint as ConstraintTokenMint,
            ConstraintTokenOwner as ConstraintTokenOwner,
            ConstraintMintMintAuthority as ConstraintMintMintAuthority,
            ConstraintMintFreezeAuthority as ConstraintMintFreezeAuthority,
            ConstraintMintDecimals as ConstraintMintDecimals,
            ConstraintSpace as ConstraintSpace,
            ConstraintAccountIsNone as ConstraintAccountIsNone,
            ConstraintTokenTokenProgram as ConstraintTokenTokenProgram,
            ConstraintMintTokenProgram as ConstraintMintTokenProgram,
            ConstraintAssociatedTokenTokenProgram as ConstraintAssociatedTokenTokenProgram,
            ConstraintMintGroupPointerExtension as ConstraintMintGroupPointerExtension,
            ConstraintMintGroupPointerExtensionAuthority as ConstraintMintGroupPointerExtensionAuthority,
            ConstraintMintGroupPointerExtensionGroupAddress as ConstraintMintGroupPointerExtensionGroupAddress,
            ConstraintMintGroupMemberPointerExtension as ConstraintMintGroupMemberPointerExtension,
            ConstraintMintGroupMemberPointerExtensionAuthority as ConstraintMintGroupMemberPointerExtensionAuthority,
            ConstraintMintGroupMemberPointerExtensionMemberAddress as ConstraintMintGroupMemberPointerExtensionMemberAddress,
            ConstraintMintMetadataPointerExtension as ConstraintMintMetadataPointerExtension,
            ConstraintMintMetadataPointerExtensionAuthority as ConstraintMintMetadataPointerExtensionAuthority,
            ConstraintMintMetadataPointerExtensionMetadataAddress as ConstraintMintMetadataPointerExtensionMetadataAddress,
            ConstraintMintCloseAuthorityExtension as ConstraintMintCloseAuthorityExtension,
            ConstraintMintCloseAuthorityExtensionAuthority as ConstraintMintCloseAuthorityExtensionAuthority,
            ConstraintMintPermanentDelegateExtension as ConstraintMintPermanentDelegateExtension,
            ConstraintMintPermanentDelegateExtensionDelegate as ConstraintMintPermanentDelegateExtensionDelegate,
            ConstraintMintTransferHookExtension as ConstraintMintTransferHookExtension,
            ConstraintMintTransferHookExtensionAuthority as ConstraintMintTransferHookExtensionAuthority,
            ConstraintMintTransferHookExtensionProgramId as ConstraintMintTransferHookExtensionProgramId,
            RequireViolated as RequireViolated,
            RequireEqViolated as RequireEqViolated,
            RequireKeysEqViolated as RequireKeysEqViolated,
            RequireNeqViolated as RequireNeqViolated,
            RequireKeysNeqViolated as RequireKeysNeqViolated,
            RequireGtViolated as RequireGtViolated,
            RequireGteViolated as RequireGteViolated,
            AccountDiscriminatorAlreadySet as AccountDiscriminatorAlreadySet,
            AccountDiscriminatorNotFound as AccountDiscriminatorNotFound,
            AccountDiscriminatorMismatch as AccountDiscriminatorMismatch,
            AccountDidNotDeserialize as AccountDidNotDeserialize,
            AccountDidNotSerialize as AccountDidNotSerialize,
            AccountNotEnoughKeys as AccountNotEnoughKeys,
            AccountNotMutable as AccountNotMutable,
            AccountOwnedByWrongProgram as AccountOwnedByWrongProgram,
            InvalidProgramId as InvalidProgramId,
            InvalidProgramExecutable as InvalidProgramExecutable,
            AccountNotSigner as AccountNotSigner,
            AccountNotSystemOwned as AccountNotSystemOwned,
            AccountNotInitialized as AccountNotInitialized,
            AccountNotProgramData as AccountNotProgramData,
            AccountNotAssociatedTokenAccount as AccountNotAssociatedTokenAccount,
            AccountSysvarMismatch as AccountSysvarMismatch,
            AccountReallocExceedsLimit as AccountReallocExceedsLimit,
            AccountDuplicateReallocs as AccountDuplicateReallocs,
            DeclaredProgramIdMismatch as DeclaredProgramIdMismatch,
            TryingToInitPayerAsProgramAccount as TryingToInitPayerAsProgramAccount,
            InvalidNumericConversion as InvalidNumericConversion,
            Deprecated as Deprecated,
        )
        # <<<GEN:anchor<<<


class ProgramError(TransactionFailed):
    """Base for program-defined errors (Custom codes, typically >= 6000).
    Each generated program gets a ``<Program>Error`` subclass of this."""


class UnknownError(TransactionFailed):
    """A ``Custom(code)`` that matched no registered program and no framework
    table — surfaced with its bare ``code`` rather than an invented name."""


# --- builtin (native) program error bases ---------------------------------- #
class SystemProgramError(ProgramError):
    """An error from the native System Program (its ``SystemError`` enum). Distinct
    from ``SolanaError.AccountInUse`` (a tx-level account-lock conflict): e.g.
    ``SystemProgramError.AccountAlreadyInUse`` is System rejecting an allocate/create
    of an account that already exists."""

    if TYPE_CHECKING:
        # >>>GEN:system>>>
        from ._errors_catalog.system import (
            AccountAlreadyInUse as AccountAlreadyInUse,
            ResultWithNegativeLamports as ResultWithNegativeLamports,
            InvalidProgramId as InvalidProgramId,
            InvalidAccountDataLength as InvalidAccountDataLength,
            MaxSeedLengthExceeded as MaxSeedLengthExceeded,
            AddressWithSeedMismatch as AddressWithSeedMismatch,
            NonceNoRecentBlockhashes as NonceNoRecentBlockhashes,
            NonceBlockhashNotExpired as NonceBlockhashNotExpired,
            NonceUnexpectedBlockhashValue as NonceUnexpectedBlockhashValue,
        )
        # <<<GEN:system<<<


class TokenError(ProgramError):
    """An error from the SPL Token program (its ``TokenError`` enum); Token-2022
    shares these base variants."""

    if TYPE_CHECKING:
        # >>>GEN:token>>>
        from ._errors_catalog.token import (
            NotRentExempt as NotRentExempt,
            InsufficientFunds as InsufficientFunds,
            InvalidMint as InvalidMint,
            MintMismatch as MintMismatch,
            OwnerMismatch as OwnerMismatch,
            FixedSupply as FixedSupply,
            AlreadyInUse as AlreadyInUse,
            InvalidNumberOfProvidedSigners as InvalidNumberOfProvidedSigners,
            InvalidNumberOfRequiredSigners as InvalidNumberOfRequiredSigners,
            UninitializedState as UninitializedState,
            NativeNotSupported as NativeNotSupported,
            NonNativeHasBalance as NonNativeHasBalance,
            InvalidInstruction as InvalidInstruction,
            InvalidState as InvalidState,
            Overflow as Overflow,
            AuthorityTypeNotSupported as AuthorityTypeNotSupported,
            MintCannotFreeze as MintCannotFreeze,
            AccountFrozen as AccountFrozen,
            MintDecimalsMismatch as MintDecimalsMismatch,
            NonNativeNotSupported as NonNativeNotSupported,
        )
        # <<<GEN:token<<<
