# @generated by solana_fuzzer._gen.errors_catalog — do not edit.
"""Static catalogs of the built-in error classes (native / Anchor / System / Token).

One real ``class`` per bundled error, so ``AnchorError.ConstraintSeeds`` and friends are
visible to type checkers. Generated from ``solana_fuzzer._gen.errors_catalog`` — do not edit."""
