# @generated by solana_fuzzer._gen.errors_catalog — do not edit.
"""Anchor framework error catalog (built-in codes < 6000).

Generated from ``solana_fuzzer._gen.errors_catalog`` — do not edit."""


from __future__ import annotations


from .._errors_base import AnchorError


class InstructionMissing(AnchorError):
    code = 100


class InstructionFallbackNotFound(AnchorError):
    code = 101


class InstructionDidNotDeserialize(AnchorError):
    code = 102


class InstructionDidNotSerialize(AnchorError):
    code = 103


class IdlInstructionStub(AnchorError):
    code = 1000


class IdlInstructionInvalidProgram(AnchorError):
    code = 1001


class IdlAccountNotEmpty(AnchorError):
    code = 1002


class EventInstructionStub(AnchorError):
    code = 1500


class ConstraintMut(AnchorError):
    code = 2000


class ConstraintHasOne(AnchorError):
    code = 2001


class ConstraintSigner(AnchorError):
    code = 2002


class ConstraintRaw(AnchorError):
    code = 2003


class ConstraintOwner(AnchorError):
    code = 2004


class ConstraintRentExempt(AnchorError):
    code = 2005


class ConstraintSeeds(AnchorError):
    code = 2006


class ConstraintExecutable(AnchorError):
    code = 2007


class ConstraintState(AnchorError):
    code = 2008


class ConstraintAssociated(AnchorError):
    code = 2009


class ConstraintAssociatedInit(AnchorError):
    code = 2010


class ConstraintClose(AnchorError):
    code = 2011


class ConstraintAddress(AnchorError):
    code = 2012


class ConstraintZero(AnchorError):
    code = 2013


class ConstraintTokenMint(AnchorError):
    code = 2014


class ConstraintTokenOwner(AnchorError):
    code = 2015


class ConstraintMintMintAuthority(AnchorError):
    code = 2016


class ConstraintMintFreezeAuthority(AnchorError):
    code = 2017


class ConstraintMintDecimals(AnchorError):
    code = 2018


class ConstraintSpace(AnchorError):
    code = 2019


class ConstraintAccountIsNone(AnchorError):
    code = 2020


class ConstraintTokenTokenProgram(AnchorError):
    code = 2021


class ConstraintMintTokenProgram(AnchorError):
    code = 2022


class ConstraintAssociatedTokenTokenProgram(AnchorError):
    code = 2023


class ConstraintMintGroupPointerExtension(AnchorError):
    code = 2024


class ConstraintMintGroupPointerExtensionAuthority(AnchorError):
    code = 2025


class ConstraintMintGroupPointerExtensionGroupAddress(AnchorError):
    code = 2026


class ConstraintMintGroupMemberPointerExtension(AnchorError):
    code = 2027


class ConstraintMintGroupMemberPointerExtensionAuthority(AnchorError):
    code = 2028


class ConstraintMintGroupMemberPointerExtensionMemberAddress(AnchorError):
    code = 2029


class ConstraintMintMetadataPointerExtension(AnchorError):
    code = 2030


class ConstraintMintMetadataPointerExtensionAuthority(AnchorError):
    code = 2031


class ConstraintMintMetadataPointerExtensionMetadataAddress(AnchorError):
    code = 2032


class ConstraintMintCloseAuthorityExtension(AnchorError):
    code = 2033


class ConstraintMintCloseAuthorityExtensionAuthority(AnchorError):
    code = 2034


class ConstraintMintPermanentDelegateExtension(AnchorError):
    code = 2035


class ConstraintMintPermanentDelegateExtensionDelegate(AnchorError):
    code = 2036


class ConstraintMintTransferHookExtension(AnchorError):
    code = 2037


class ConstraintMintTransferHookExtensionAuthority(AnchorError):
    code = 2038


class ConstraintMintTransferHookExtensionProgramId(AnchorError):
    code = 2039


class RequireViolated(AnchorError):
    code = 2500


class RequireEqViolated(AnchorError):
    code = 2501


class RequireKeysEqViolated(AnchorError):
    code = 2502


class RequireNeqViolated(AnchorError):
    code = 2503


class RequireKeysNeqViolated(AnchorError):
    code = 2504


class RequireGtViolated(AnchorError):
    code = 2505


class RequireGteViolated(AnchorError):
    code = 2506


class AccountDiscriminatorAlreadySet(AnchorError):
    code = 3000


class AccountDiscriminatorNotFound(AnchorError):
    code = 3001


class AccountDiscriminatorMismatch(AnchorError):
    code = 3002


class AccountDidNotDeserialize(AnchorError):
    code = 3003


class AccountDidNotSerialize(AnchorError):
    code = 3004


class AccountNotEnoughKeys(AnchorError):
    code = 3005


class AccountNotMutable(AnchorError):
    code = 3006


class AccountOwnedByWrongProgram(AnchorError):
    code = 3007


class InvalidProgramId(AnchorError):
    code = 3008


class InvalidProgramExecutable(AnchorError):
    code = 3009


class AccountNotSigner(AnchorError):
    code = 3010


class AccountNotSystemOwned(AnchorError):
    code = 3011


class AccountNotInitialized(AnchorError):
    code = 3012


class AccountNotProgramData(AnchorError):
    code = 3013


class AccountNotAssociatedTokenAccount(AnchorError):
    code = 3014


class AccountSysvarMismatch(AnchorError):
    code = 3015


class AccountReallocExceedsLimit(AnchorError):
    code = 3016


class AccountDuplicateReallocs(AnchorError):
    code = 3017


class DeclaredProgramIdMismatch(AnchorError):
    code = 4100


class TryingToInitPayerAsProgramAccount(AnchorError):
    code = 4101


class InvalidNumericConversion(AnchorError):
    code = 4102


class Deprecated(AnchorError):
    code = 5000


BY_CODE: dict[int, type[AnchorError]] = {
    100: InstructionMissing,
    101: InstructionFallbackNotFound,
    102: InstructionDidNotDeserialize,
    103: InstructionDidNotSerialize,
    1000: IdlInstructionStub,
    1001: IdlInstructionInvalidProgram,
    1002: IdlAccountNotEmpty,
    1500: EventInstructionStub,
    2000: ConstraintMut,
    2001: ConstraintHasOne,
    2002: ConstraintSigner,
    2003: ConstraintRaw,
    2004: ConstraintOwner,
    2005: ConstraintRentExempt,
    2006: ConstraintSeeds,
    2007: ConstraintExecutable,
    2008: ConstraintState,
    2009: ConstraintAssociated,
    2010: ConstraintAssociatedInit,
    2011: ConstraintClose,
    2012: ConstraintAddress,
    2013: ConstraintZero,
    2014: ConstraintTokenMint,
    2015: ConstraintTokenOwner,
    2016: ConstraintMintMintAuthority,
    2017: ConstraintMintFreezeAuthority,
    2018: ConstraintMintDecimals,
    2019: ConstraintSpace,
    2020: ConstraintAccountIsNone,
    2021: ConstraintTokenTokenProgram,
    2022: ConstraintMintTokenProgram,
    2023: ConstraintAssociatedTokenTokenProgram,
    2024: ConstraintMintGroupPointerExtension,
    2025: ConstraintMintGroupPointerExtensionAuthority,
    2026: ConstraintMintGroupPointerExtensionGroupAddress,
    2027: ConstraintMintGroupMemberPointerExtension,
    2028: ConstraintMintGroupMemberPointerExtensionAuthority,
    2029: ConstraintMintGroupMemberPointerExtensionMemberAddress,
    2030: ConstraintMintMetadataPointerExtension,
    2031: ConstraintMintMetadataPointerExtensionAuthority,
    2032: ConstraintMintMetadataPointerExtensionMetadataAddress,
    2033: ConstraintMintCloseAuthorityExtension,
    2034: ConstraintMintCloseAuthorityExtensionAuthority,
    2035: ConstraintMintPermanentDelegateExtension,
    2036: ConstraintMintPermanentDelegateExtensionDelegate,
    2037: ConstraintMintTransferHookExtension,
    2038: ConstraintMintTransferHookExtensionAuthority,
    2039: ConstraintMintTransferHookExtensionProgramId,
    2500: RequireViolated,
    2501: RequireEqViolated,
    2502: RequireKeysEqViolated,
    2503: RequireNeqViolated,
    2504: RequireKeysNeqViolated,
    2505: RequireGtViolated,
    2506: RequireGteViolated,
    3000: AccountDiscriminatorAlreadySet,
    3001: AccountDiscriminatorNotFound,
    3002: AccountDiscriminatorMismatch,
    3003: AccountDidNotDeserialize,
    3004: AccountDidNotSerialize,
    3005: AccountNotEnoughKeys,
    3006: AccountNotMutable,
    3007: AccountOwnedByWrongProgram,
    3008: InvalidProgramId,
    3009: InvalidProgramExecutable,
    3010: AccountNotSigner,
    3011: AccountNotSystemOwned,
    3012: AccountNotInitialized,
    3013: AccountNotProgramData,
    3014: AccountNotAssociatedTokenAccount,
    3015: AccountSysvarMismatch,
    3016: AccountReallocExceedsLimit,
    3017: AccountDuplicateReallocs,
    4100: DeclaredProgramIdMismatch,
    4101: TryingToInitPayerAsProgramAccount,
    4102: InvalidNumericConversion,
    5000: Deprecated,
}
