# @generated by solana_fuzzer._gen.errors_catalog — do not edit.
"""Native Solana runtime error catalog (name-keyed; no numeric code).

Generated from ``solana_fuzzer._gen.errors_catalog`` — do not edit."""


from __future__ import annotations


from .._errors_base import SolanaError


class GenericError(SolanaError):
    pass


class InvalidArgument(SolanaError):
    pass


class InvalidInstructionData(SolanaError):
    pass


class InvalidAccountData(SolanaError):
    pass


class AccountDataTooSmall(SolanaError):
    pass


class InsufficientFunds(SolanaError):
    pass


class IncorrectProgramId(SolanaError):
    pass


class MissingRequiredSignature(SolanaError):
    pass


class AccountAlreadyInitialized(SolanaError):
    pass


class UninitializedAccount(SolanaError):
    pass


class UnbalancedInstruction(SolanaError):
    pass


class ModifiedProgramId(SolanaError):
    pass


class ExternalAccountLamportSpend(SolanaError):
    pass


class ExternalAccountDataModified(SolanaError):
    pass


class ReadonlyLamportChange(SolanaError):
    pass


class ReadonlyDataModified(SolanaError):
    pass


class DuplicateAccountIndex(SolanaError):
    pass


class ExecutableModified(SolanaError):
    pass


class RentEpochModified(SolanaError):
    pass


class NotEnoughAccountKeys(SolanaError):
    pass


class AccountDataSizeChanged(SolanaError):
    pass


class AccountNotExecutable(SolanaError):
    pass


class AccountBorrowFailed(SolanaError):
    pass


class AccountBorrowOutstanding(SolanaError):
    pass


class DuplicateAccountOutOfSync(SolanaError):
    pass


class InvalidError(SolanaError):
    pass


class ExecutableDataModified(SolanaError):
    pass


class ExecutableLamportChange(SolanaError):
    pass


class ExecutableAccountNotRentExempt(SolanaError):
    pass


class UnsupportedProgramId(SolanaError):
    pass


class CallDepth(SolanaError):
    pass


class MissingAccount(SolanaError):
    pass


class ReentrancyNotAllowed(SolanaError):
    pass


class MaxSeedLengthExceeded(SolanaError):
    pass


class InvalidSeeds(SolanaError):
    pass


class InvalidRealloc(SolanaError):
    pass


class ComputationalBudgetExceeded(SolanaError):
    pass


class PrivilegeEscalation(SolanaError):
    pass


class ProgramEnvironmentSetupFailure(SolanaError):
    pass


class ProgramFailedToComplete(SolanaError):
    pass


class ProgramFailedToCompile(SolanaError):
    pass


class Immutable(SolanaError):
    pass


class IncorrectAuthority(SolanaError):
    pass


class BorshIoError(SolanaError):
    pass


class AccountNotRentExempt(SolanaError):
    pass


class InvalidAccountOwner(SolanaError):
    pass


class ArithmeticOverflow(SolanaError):
    pass


class UnsupportedSysvar(SolanaError):
    pass


class IllegalOwner(SolanaError):
    pass


class MaxAccountsDataAllocationsExceeded(SolanaError):
    pass


class MaxAccountsExceeded(SolanaError):
    pass


class MaxInstructionTraceLengthExceeded(SolanaError):
    pass


class BuiltinProgramsMustConsumeComputeUnits(SolanaError):
    pass


class AccountInUse(SolanaError):
    pass


class AccountLoadedTwice(SolanaError):
    pass


class AccountNotFound(SolanaError):
    pass


class ProgramAccountNotFound(SolanaError):
    pass


class InsufficientFundsForFee(SolanaError):
    pass


class InvalidAccountForFee(SolanaError):
    pass


class AlreadyProcessed(SolanaError):
    pass


class BlockhashNotFound(SolanaError):
    pass


class CallChainTooDeep(SolanaError):
    pass


class MissingSignatureForFee(SolanaError):
    pass


class InvalidAccountIndex(SolanaError):
    pass


class SignatureFailure(SolanaError):
    pass


class InvalidProgramForExecution(SolanaError):
    pass


class SanitizeFailure(SolanaError):
    pass


class ClusterMaintenance(SolanaError):
    pass


class WouldExceedMaxBlockCostLimit(SolanaError):
    pass


class UnsupportedVersion(SolanaError):
    pass


class InvalidWritableAccount(SolanaError):
    pass


class WouldExceedMaxAccountCostLimit(SolanaError):
    pass


class WouldExceedAccountDataBlockLimit(SolanaError):
    pass


class TooManyAccountLocks(SolanaError):
    pass


class AddressLookupTableNotFound(SolanaError):
    pass


class InvalidAddressLookupTableOwner(SolanaError):
    pass


class InvalidAddressLookupTableData(SolanaError):
    pass


class InvalidAddressLookupTableIndex(SolanaError):
    pass


class InvalidRentPayingAccount(SolanaError):
    pass


class WouldExceedMaxVoteCostLimit(SolanaError):
    pass


class WouldExceedAccountDataTotalLimit(SolanaError):
    pass


class DuplicateInstruction(SolanaError):
    pass


class InsufficientFundsForRent(SolanaError):
    pass


class MaxLoadedAccountsDataSizeExceeded(SolanaError):
    pass


class InvalidLoadedAccountsDataSizeLimit(SolanaError):
    pass


class ResanitizationNeeded(SolanaError):
    pass


class ProgramExecutionTemporarilyRestricted(SolanaError):
    pass


class UnbalancedTransaction(SolanaError):
    pass


class ProgramCacheHitMaxLimit(SolanaError):
    pass


class CommitCancelled(SolanaError):
    pass


BY_NAME: dict[str, type[SolanaError]] = {
    'GenericError': GenericError,
    'InvalidArgument': InvalidArgument,
    'InvalidInstructionData': InvalidInstructionData,
    'InvalidAccountData': InvalidAccountData,
    'AccountDataTooSmall': AccountDataTooSmall,
    'InsufficientFunds': InsufficientFunds,
    'IncorrectProgramId': IncorrectProgramId,
    'MissingRequiredSignature': MissingRequiredSignature,
    'AccountAlreadyInitialized': AccountAlreadyInitialized,
    'UninitializedAccount': UninitializedAccount,
    'UnbalancedInstruction': UnbalancedInstruction,
    'ModifiedProgramId': ModifiedProgramId,
    'ExternalAccountLamportSpend': ExternalAccountLamportSpend,
    'ExternalAccountDataModified': ExternalAccountDataModified,
    'ReadonlyLamportChange': ReadonlyLamportChange,
    'ReadonlyDataModified': ReadonlyDataModified,
    'DuplicateAccountIndex': DuplicateAccountIndex,
    'ExecutableModified': ExecutableModified,
    'RentEpochModified': RentEpochModified,
    'NotEnoughAccountKeys': NotEnoughAccountKeys,
    'AccountDataSizeChanged': AccountDataSizeChanged,
    'AccountNotExecutable': AccountNotExecutable,
    'AccountBorrowFailed': AccountBorrowFailed,
    'AccountBorrowOutstanding': AccountBorrowOutstanding,
    'DuplicateAccountOutOfSync': DuplicateAccountOutOfSync,
    'InvalidError': InvalidError,
    'ExecutableDataModified': ExecutableDataModified,
    'ExecutableLamportChange': ExecutableLamportChange,
    'ExecutableAccountNotRentExempt': ExecutableAccountNotRentExempt,
    'UnsupportedProgramId': UnsupportedProgramId,
    'CallDepth': CallDepth,
    'MissingAccount': MissingAccount,
    'ReentrancyNotAllowed': ReentrancyNotAllowed,
    'MaxSeedLengthExceeded': MaxSeedLengthExceeded,
    'InvalidSeeds': InvalidSeeds,
    'InvalidRealloc': InvalidRealloc,
    'ComputationalBudgetExceeded': ComputationalBudgetExceeded,
    'PrivilegeEscalation': PrivilegeEscalation,
    'ProgramEnvironmentSetupFailure': ProgramEnvironmentSetupFailure,
    'ProgramFailedToComplete': ProgramFailedToComplete,
    'ProgramFailedToCompile': ProgramFailedToCompile,
    'Immutable': Immutable,
    'IncorrectAuthority': IncorrectAuthority,
    'BorshIoError': BorshIoError,
    'AccountNotRentExempt': AccountNotRentExempt,
    'InvalidAccountOwner': InvalidAccountOwner,
    'ArithmeticOverflow': ArithmeticOverflow,
    'UnsupportedSysvar': UnsupportedSysvar,
    'IllegalOwner': IllegalOwner,
    'MaxAccountsDataAllocationsExceeded': MaxAccountsDataAllocationsExceeded,
    'MaxAccountsExceeded': MaxAccountsExceeded,
    'MaxInstructionTraceLengthExceeded': MaxInstructionTraceLengthExceeded,
    'BuiltinProgramsMustConsumeComputeUnits': BuiltinProgramsMustConsumeComputeUnits,
    'AccountInUse': AccountInUse,
    'AccountLoadedTwice': AccountLoadedTwice,
    'AccountNotFound': AccountNotFound,
    'ProgramAccountNotFound': ProgramAccountNotFound,
    'InsufficientFundsForFee': InsufficientFundsForFee,
    'InvalidAccountForFee': InvalidAccountForFee,
    'AlreadyProcessed': AlreadyProcessed,
    'BlockhashNotFound': BlockhashNotFound,
    'CallChainTooDeep': CallChainTooDeep,
    'MissingSignatureForFee': MissingSignatureForFee,
    'InvalidAccountIndex': InvalidAccountIndex,
    'SignatureFailure': SignatureFailure,
    'InvalidProgramForExecution': InvalidProgramForExecution,
    'SanitizeFailure': SanitizeFailure,
    'ClusterMaintenance': ClusterMaintenance,
    'WouldExceedMaxBlockCostLimit': WouldExceedMaxBlockCostLimit,
    'UnsupportedVersion': UnsupportedVersion,
    'InvalidWritableAccount': InvalidWritableAccount,
    'WouldExceedMaxAccountCostLimit': WouldExceedMaxAccountCostLimit,
    'WouldExceedAccountDataBlockLimit': WouldExceedAccountDataBlockLimit,
    'TooManyAccountLocks': TooManyAccountLocks,
    'AddressLookupTableNotFound': AddressLookupTableNotFound,
    'InvalidAddressLookupTableOwner': InvalidAddressLookupTableOwner,
    'InvalidAddressLookupTableData': InvalidAddressLookupTableData,
    'InvalidAddressLookupTableIndex': InvalidAddressLookupTableIndex,
    'InvalidRentPayingAccount': InvalidRentPayingAccount,
    'WouldExceedMaxVoteCostLimit': WouldExceedMaxVoteCostLimit,
    'WouldExceedAccountDataTotalLimit': WouldExceedAccountDataTotalLimit,
    'DuplicateInstruction': DuplicateInstruction,
    'InsufficientFundsForRent': InsufficientFundsForRent,
    'MaxLoadedAccountsDataSizeExceeded': MaxLoadedAccountsDataSizeExceeded,
    'InvalidLoadedAccountsDataSizeLimit': InvalidLoadedAccountsDataSizeLimit,
    'ResanitizationNeeded': ResanitizationNeeded,
    'ProgramExecutionTemporarilyRestricted': ProgramExecutionTemporarilyRestricted,
    'UnbalancedTransaction': UnbalancedTransaction,
    'ProgramCacheHitMaxLimit': ProgramCacheHitMaxLimit,
    'CommitCancelled': CommitCancelled,
}
