# @generated by solana_fuzzer._gen.errors_catalog — do not edit.
"""SPL Token / Token-2022 error catalog.

Generated from ``solana_fuzzer._gen.errors_catalog`` — do not edit."""


from __future__ import annotations


from .._errors_base import TokenError


class NotRentExempt(TokenError):
    code = 0
    msg = 'lamport balance below rent-exempt threshold'


class InsufficientFunds(TokenError):
    code = 1
    msg = 'insufficient funds'


class InvalidMint(TokenError):
    code = 2
    msg = 'invalid mint'


class MintMismatch(TokenError):
    code = 3
    msg = 'account not associated with this mint'


class OwnerMismatch(TokenError):
    code = 4
    msg = 'owner does not match'


class FixedSupply(TokenError):
    code = 5
    msg = 'fixed supply'


class AlreadyInUse(TokenError):
    code = 6
    msg = 'already in use'


class InvalidNumberOfProvidedSigners(TokenError):
    code = 7
    msg = 'invalid number of provided signers'


class InvalidNumberOfRequiredSigners(TokenError):
    code = 8
    msg = 'invalid number of required signers'


class UninitializedState(TokenError):
    code = 9
    msg = 'state is uninitialized'


class NativeNotSupported(TokenError):
    code = 10
    msg = 'instruction does not support native tokens'


class NonNativeHasBalance(TokenError):
    code = 11
    msg = 'non-native account can only be closed if its balance is zero'


class InvalidInstruction(TokenError):
    code = 12
    msg = 'invalid instruction'


class InvalidState(TokenError):
    code = 13
    msg = 'state is invalid for requested operation'


class Overflow(TokenError):
    code = 14
    msg = 'operation overflowed'


class AuthorityTypeNotSupported(TokenError):
    code = 15
    msg = 'account does not support specified authority type'


class MintCannotFreeze(TokenError):
    code = 16
    msg = 'this token mint cannot freeze accounts'


class AccountFrozen(TokenError):
    code = 17
    msg = 'account is frozen'


class MintDecimalsMismatch(TokenError):
    code = 18
    msg = 'the provided decimals value different from the mint decimals'


class NonNativeNotSupported(TokenError):
    code = 19
    msg = 'instruction does not support non-native tokens'


BY_CODE: dict[int, type[TokenError]] = {
    0: NotRentExempt,
    1: InsufficientFunds,
    2: InvalidMint,
    3: MintMismatch,
    4: OwnerMismatch,
    5: FixedSupply,
    6: AlreadyInUse,
    7: InvalidNumberOfProvidedSigners,
    8: InvalidNumberOfRequiredSigners,
    9: UninitializedState,
    10: NativeNotSupported,
    11: NonNativeHasBalance,
    12: InvalidInstruction,
    13: InvalidState,
    14: Overflow,
    15: AuthorityTypeNotSupported,
    16: MintCannotFreeze,
    17: AccountFrozen,
    18: MintDecimalsMismatch,
    19: NonNativeNotSupported,
}
